### ISSUE TITLE
Exception in onLogin callback: Error: ID is required

### ISSUE THREAD

**Issue by Nakroma** [mizzao/meteor-user-status#110]
Hey,  
I left my project alone for some time, today I came back and I get an error when I try to log in with a user:

```
I20161218-18:09:15.804(1)? Exception in onLogin callback: Error: ID is required  
I20161218-18:09:15.805(1)?     at getErrorObject (packages\aldeed_collection2-core.js:480:15)  
I20161218-18:09:15.805(1)?     at [object Object].doValidate (packages\aldeed_collection2-core.js:462:13)  
I20161218-18:09:15.805(1)?     at [object Object].Mongo.Collection.(anonymous function) [as insert](packages\aldeed_collection2-core.js:214:25)  
I20161218-18:09:15.805(1)?     at _squadCreate (imports/api/squad.js:173:32)  
I20161218-18:09:15.805(1)?     at EventEmitter.<anonymous> (imports/api/squad.js:97:13)  
I20161218-18:09:15.806(1)?     at emitOne (events.js:82:20)  
I20161218-18:09:15.806(1)?     at EventEmitter.emit (events.js:169:7)  
I20161218-18:09:15.806(1)?     at loginSession (packages/mizzao_user-status/status.coffee:133:16)  
I20161218-18:09:15.806(1)?     at packages/mizzao_user-status/status.coffee:204:3  
I20161218-18:09:15.806(1)?     at runAndHandleExceptions (packages\callback-hook.js:152:24)
```

It seems theres an error on Accounts.onLogin in status.coffee's line 204.  
For reference, heres my code which uses the connectionLogin onevent:
```
// Listen for login and create new squad
    UserStatus.events.on('connectionLogin', function(fields) {
        const user = Meteor.users.findOne(fields.userId);
        if (!user.hasOwnProperty('squadId')) {
            // This should be called for a new user, instead it throws the error above
            squadCreate(fields.userId);
        } else {
            // Ignore
        }
    });
```

Im using the newest meteor and newest user-status version (ran meteor update --all-packages earlier, didnt change a thing)

**Comment by davidalekna** [comment]
Meteor.users.find(this.userId) instead of your Meteor.users.findOne(fields.userId) and it should work

**Comment by Nakroma** [comment]
Sadly not, same error

**Comment by Nakroma** [comment]
Was an error with my schema which I oversaw
