### ISSUE TITLE
MinimongoError: You cannot currently mix including and excluding fields.

### ISSUE THREAD

**Issue by cope** [mizzao/meteor-user-status#76]
Hi, I installed user-status and it always throws the same error:

I20150816-15:24:36.508(2)? Exception from sub online id u3hfrAktf49WEEeXZ MinimongoError: You cannot currently mix including and excluding fields.
I20150816-15:24:36.508(2)?     at MinimongoError (packages/minimongo/minimongo.js:53:1)
I20150816-15:24:36.508(2)?     at packages/minimongo/projection.js:75:1
I20150816-15:24:36.508(2)?     at Array.forEach (native)
I20150816-15:24:36.508(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150816-15:24:36.508(2)?     at projectionDetails (packages/minimongo/projection.js:69:1)
I20150816-15:24:36.508(2)?     at Function.LocalCollection._compileProjection (packages/minimongo/projection.js:12:1)
I20150816-15:24:36.508(2)?     at new OplogObserveDriver (packages/mongo/oplog_observe_driver.js:87:1)
I20150816-15:24:36.509(2)?     at [object Object].MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1164:1)
I20150816-15:24:36.509(2)?     at [object Object].Cursor.observeChanges (packages/mongo/mongo_driver.js:854:1)
I20150816-15:24:36.509(2)?     at Function.Mongo.Collection._publishCursor (packages/mongo/collection.js:303:1)

My first guess is that it conflicts with some other meteor package?

These are my packages:

 meteor-platform
 yuukan:streamy
 yuukan:streamy-rooms
 accounts-base
 accounts-facebook
 service-configuration
 iron:router
 http
 mizzao:user-status

**Comment by cope** [comment]
I think this has nothing to do with user-status, but rather with me not having enough experience with meteorjs. I played around with my publishing/subscribing collections and the above error was gone and everything works as expected.
