### ISSUE TITLE
Security Issue : Server Crashes if users updates status in terminal

### ISSUE THREAD

**Issue by patrickml** [mizzao/meteor-user-status#85]
Go to the terminal in Chrome and run `Meteor.users.update({ _id : Meteor.userId() }, { $set : { 'status' : "hacked" } })`
~~~
 /Users/patricklewis/.meteor/packages/meteor-tool/.1.1.9.1az1gbv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20151001-12:55:32.688(-4)? (STDERR)                                            throw(ex);
W20151001-12:55:32.688(-4)? (STDERR)                                                  ^
W20151001-12:55:32.689(-4)? (STDERR) MongoError: cannot use the part (status of status.online) to traverse the element ({status: "active"})
W20151001-12:55:32.689(-4)? (STDERR)     at Object.Future.wait (/Users/patricklewis/.meteor/packages/meteor-tool/.1.1.9.1az1gbv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20151001-12:55:32.689(-4)? (STDERR)     at [object Object].<anonymous> (meteor://💻app/packages/meteor/helpers.js:119:1)
W20151001-12:55:32.689(-4)? (STDERR)     at [object Object].MongoConnection.(anonymous function) [as update] (meteor://💻app/packages/mongo/mongo_driver.js:736:1)
W20151001-12:55:32.689(-4)? (STDERR)     at Object.CollectionHooks.defineAdvice.self (meteor://💻app/packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:457:1)
W20151001-12:55:32.689(-4)? (STDERR)     at Object.collection.(anonymous function) [as update] (meteor://💻app/packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:125:1)
W20151001-12:55:32.689(-4)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (meteor://💻app/packages/mongo/collection.js:586:1)
W20151001-12:55:32.689(-4)? (STDERR)     at onStartup (meteor://💻app/packages/mizzao_user-status/status.coffee:102:16)
W20151001-12:55:32.690(-4)? (STDERR)     at /Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/boot.js:249:5
W20151001-12:55:32.690(-4)? (STDERR)     - - - - -
W20151001-12:55:32.690(-4)? (STDERR)     at Object.toError (/Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
W20151001-12:55:32.690(-4)? (STDERR)     at /Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
W20151001-12:55:32.690(-4)? (STDERR)     at /Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1197:7
W20151001-12:55:32.690(-4)? (STDERR)     at /Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
W20151001-12:55:32.691(-4)? (STDERR)     at Server.Base._callHandler (/Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
W20151001-12:55:32.691(-4)? (STDERR)     at /Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
W20151001-12:55:32.691(-4)? (STDERR)     at [object Object].MongoReply.parseBody (/Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
W20151001-12:55:32.691(-4)? (STDERR)     at [object Object].<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
W20151001-12:55:32.691(-4)? (STDERR)     at [object Object].emit (events.js:95:17)
W20151001-12:55:32.692(-4)? (STDERR)     at [object Object].<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
W20151001-12:55:32.692(-4)? (STDERR)     at [object Object].emit (events.js:98:17)
W20151001-12:55:32.692(-4)? (STDERR)     at Socket.<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.4.39_1.a5c0vn++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
W20151001-12:55:32.692(-4)? (STDERR)     at Socket.emit (events.js:95:17)
W20151001-12:55:32.692(-4)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20151001-12:55:32.692(-4)? (STDERR)     at Socket.emit (events.js:92:17)
W20151001-12:55:32.692(-4)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20151001-12:55:32.692(-4)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20151001-12:55:32.692(-4)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20151001-12:55:32.693(-4)? (STDERR)     at Socket.Readable.push (_stream_readable.js:128:10)
W20151001-12:55:32.693(-4)? (STDERR)     at TCP.onread (net.js:529:21)
=> Exited with code: 8
   Starting your app                         -

~~~

At first you will just see an error, but then try to restart your server.

**Comment by mizzao** [comment]
I don't think users should be able to update their `status` field. Any chance you are using the `insecure` package on a default meteor app?

**Comment by patrickml** [comment]
Nope :/ https://www.dropbox.com/s/ba02kqboof0v33t/Screenshot%202015-10-01%2014.33.49.png?dl=0

**Comment by mizzao** [comment]
Did you set up too broad of an `allow` rule on `Meteor.users`?

**Comment by patrickml** [comment]
Yeh that could be but I thought they merged?

~~~
Meteor.users.allow({
  insert : function (userId, doc) {
    return true;
  },
  update : function (userId, doc, fieldNames, modifier) {
    return userId === doc._id || Roles.userHasPermission(userId, 'update.users');
  },
  remove : function (userId, doc) {
    return false;
  }
});
~~~

**Comment by mizzao** [comment]
There is no explict `deny` rule set up for the status field, so if you set up an `allow` field you need to make sure that users can't do what you don't expect. Right now, under your rule, a user that can edit can even change their own `userId` or login tokens, among other things.

This is what happens if I try what you did in the demo app with `insecure` removed:

![image](https://cloud.githubusercontent.com/assets/2080084/10230349/9415dece-684a-11e5-9fad-dc491d8f539e.png)

**Comment by patrickml** [comment]
@mizzao Thank you i guess its a good thing i ran into this issue. I thought that allow deny rules combined

https://github.com/meteor/meteor/blob/0cd577f8c6407e519f72c479380a75923ce4e347/packages/mongo/collection.js#L727

**Comment by mizzao** [comment]
They do combine, there is just no `deny` rule set to begin with.
